# A TensorFlow workflow
- Get data Ready
- Build or pick a pretrained Model
- Fit the model on the data and make a prediction
- Evaluate the model
- Improve through experimentation
- Save & Reload your Trained Model

In [1]:
import tensorflow as tf

# How to Approach this thing
- "If in doubt,run the code"
- "Experiment ,experiment ,experiment !!"
- "Visualize,visualize,visualize"
- "Ask a lot of dumb questions to get better !! "
- "Avoid Over Thinking the process "

## Introduction to Tensors

In [2]:
print(tf.__version__)

2.18.0


In [3]:
# Creating our first tensor with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Check  the number of dimensions of a tensor(ndim= number of dimensions)
scalar.ndim

0

In [5]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check the dimension of our vector
vector.ndim

1

In [7]:
# creating a matrix(has more than one dimension)
matrix=tf.constant([[10,7,8],[7,10,9]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  8],
       [ 7, 10,  9]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# creating another matrix
another_matrix=tf.constant([[10.,7.],[7.,9.],[5.3,6.3]],dtype=tf.float16)

In [10]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  7. ],
       [ 7. ,  9. ],
       [ 5.3,  6.3]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
# lets create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])

In [13]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

## Summary
 * Scaller : a single number
 * Vector : a number with direction (like - wind speed)
 * Matrix : a 2-d array of numbers
 * Tensor : an n-d array of numbers (where n can be anything, a 0-d tensor is a scaler, a 1-d tensor is a vector,a 2-d tensor is a matrix and so on...)

In [15]:
#another way of building a tensor
tf.Variable

tensorflow.python.ops.variables.Variable

# Creating tensors with tf.Variable

In [16]:
changable_tensor=tf.Variable([10,7])
unchangable_tensor=tf.constant([10,7])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [17]:
# lets try chnaging one of the elements in our changable tensor
changable_tensor[0].assign(104)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([104,   7], dtype=int32)>

In [18]:
#lets try changing one of the element in our unchangable tensor
# unchangable_tensor[1].assign(104) # This line caused an error because tf.constant is immutable
unchangable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

# Creating Random Tensors

In [19]:
# creating tensor with random values
random1 = tf.random.Generator.from_seed(42) # seed for reproducibility
random1 = random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [20]:
random2=tf.random.Generator.from_seed(42)
random2=random2.normal(shape=(3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [21]:
random1==random2 # same seed means same random numbers

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

# Shuffling Tensors

In [22]:
# shuffling the order in our random tensor(valuable for shuffling my data)
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])

#Shuffle our non-shuffled tensor
tf.random.set_seed(20)
tf.random.shuffle(not_shuffled,seed=27) # that means random shuffle is done based upon 2 seeds(global+local...so its inportant to define both)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [23]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [24]:
tf.random.shuffle(not_shuffled,seed=21) # here global and local are different so we are getting different in each time

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# Other ways to make tensors

In [25]:
#tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [26]:
# tensor of all zeroes
tf.zeros([7,10])

<tf.Tensor: shape=(7, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# Numpy array to Tensor

In [27]:
# you can turn numpy arrays into tensors as well...the main difference between tf and np is that ,tf can be run on gpu but np is not
import numpy as np
np_arrayA=np.arange(1,25,dtype=np.int32)
# capital for matrix or tensor
# lower for vector
np_arrayA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [28]:
A=tf.constant(np_arrayA,shape=(3,2,4)) # 3*2*4=24 so its possible ofc
A

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [29]:
A.ndim

3

# Getting more information from tensors
 * Shape => tensor.shape
 * Rank => tensor.ndim
 * axis or dimensions => tensor[0],tenso[:,1]
 * Size => tf.size(tensor)

In [30]:
# create a rank 4 tensor
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
#rank
rank_4_tensor.ndim

4

In [32]:
# 0 th axis showing up
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [33]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [34]:
2*3*4*5

120

In [35]:
# Get various attributes of our tensorflow
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions(rank):",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


# Indexing Tensors
Tensors can be indexed just like python lists

In [36]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [37]:
#get the first 2 elements of each dimensions
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [38]:
some_list

[1, 2, 3, 4]

# Get the first element from each dimension from each index except for the final one

In [39]:
some_list[:1]

[1]

In [40]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [41]:
rank_4_tensor[:1,:1,:1,:] # : means ja ase sob r baki khetre only the 0th indexed thing is getting printed

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

# adding extra dimension at the end of the tensor

In [42]:
rank_2_tensor=tf.constant([[10,7],
                           [3,9]])
print(rank_2_tensor.shape)
print(rank_2_tensor.ndim)

(2, 2)
2


In [43]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  9]], dtype=int32)>

In [44]:
some_list,some_list[-1]

([1, 2, 3, 4], 4)

In [45]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  9]], dtype=int32)>

In [46]:
# get the last item of each of the row of our rank 2 tensor
rank_2_tensor[:,-1] # : before comma means select all rows,then -1 means select last column for every row(because of : at first)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9], dtype=int32)>

In [47]:
# add in extra dimension to our rank 2 tensor
# Way 1
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 9]]], dtype=int32)>

In [48]:
# Way 2
tf.expand_dims(rank_2_tensor,axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 9]]], dtype=int32)>

In [49]:
# expand the 0th index
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  9]]], dtype=int32)>

In [50]:
# expand the 1th(in the middle) index
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  9]]], dtype=int32)>

In [51]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  9]], dtype=int32)>

# Tensor Operations

**Basic Operations**
`+`,`-`,`*`,`/`

In [52]:
# you can add values to a tensor using the addition operator
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [53]:
# original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [54]:
# subtraction
tensor-2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]], dtype=int32)>

In [55]:
# Multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [56]:
# division
tensor/3

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3.33333333, 2.33333333],
       [1.        , 1.33333333]])>

# We should use tensorflow builtin functions to get the support of gpu acceleration

In [57]:
tf.multiply(tensor,10)# tf.math,multiply

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [58]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix Multiplication**

Matrix mul is one the most common operations in tensorflow

In [59]:
# matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [60]:
# matrix multiplication using python
tensor*tensor # different answer cz its element wise multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

### practise

In [61]:
matrix_A=tf.constant([
     [1,2,5],
     [7,2,1],
     [3,3,3]
    ],dtype=tf.float32)
matrix_A.shape

TensorShape([3, 3])

In [62]:
matrix_B=tf.constant([
    [3,5],
    [6,7],
    [1,8]
],dtype=tf.float32)
matrix_B.shape

TensorShape([3, 2])

In [63]:
tf.matmul(matrix_A,matrix_B)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[20., 59.],
       [34., 57.],
       [30., 60.]], dtype=float32)>

In [64]:
# matrix multiplication with '@'operator
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [65]:
#create a tensor (3,2) tensor
X=tf.constant([
    [1,2],
    [3,4],
    [5,6]
])
#create another tensor (3,2) tensor
Y=tf.constant([
    [7,8],
    [9,10],
    [11,12]
])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [66]:
# Try to multiply tensors of same shape

# tf.matmul(X,Y)
# X@Y


# not possible cz inner dimensions don't match up

In [67]:
# Let's change the shape of Y
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [68]:
#now try to multiply X by reshaped Y
X@tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [69]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [70]:
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [71]:
tf.reshape(X,shape=(2,3)).shape,Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

**so outer shapes matched and hence we get output of outer dimensions size**

## We can do the same with transpose

In [72]:
X,tf.transpose(X),tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [73]:
# try matmul with the transposed X
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [74]:
# try matmul with the reshaped X
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

**The Dot Product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:

- `tf.matmul()`
- `tf.tensordot()`

In [75]:
#Perform the dot product of X & Y requires Traansposing one of them either X or Y
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [76]:
# Perform matrix multiplication X & Y (Transposed)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [77]:
# Check the values of Y ,reshape Y and Transpose Y
print("Normal Y:")
print(Y,"\n")
print("Y reshaped to (2,3):")
print(tf.reshape(Y,(2,3)),"\n")
print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [78]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, while performing matrix multiplication on two tensors which dont line up,we will transpose either one of them to get satisfy matrix multiplication rules !

# Changing Default Data Types of a tensor

In [79]:
# create a new tensor with default data type = float32
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [80]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [81]:
tf.__version__

'2.18.0'

In [82]:
# change from float32 to float16 (reduced precision)
D=tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [83]:
# B=tf.constant([7,10])
B.dtype

tf.float32

# Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [84]:
# Get the absolute value
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [85]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of the aggregation:
- Get min
- Get max
- Get mean of a tensor
- Get sum of a tensor


In [86]:
#create a random tensor with values between 0 & 100 of size 50
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 6, 81, 53, 86, 38, 77, 19, 80, 96, 74, 79, 79, 77, 19, 73, 71, 52,
        0, 40, 17, 99, 15, 72, 49, 92, 70, 93, 59, 64, 89, 94, 95, 23,  5,
       21, 62, 59, 86, 54, 30, 13, 88,  8, 75, 87, 41, 80,  9, 97, 61])>

In [87]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [88]:
# find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [89]:
# find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [90]:
#find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=58>

In [91]:
# find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2907>

# Calculating Variance and Standard Deviation

**Exercise :** With what we've just learned ,find the variance and standard deviation of out `E` tensor using Tensorflow methods

Variance : ` σ² = Σ (xi - μ)² / N`




In [92]:
def compute_variance(x,axis=None,keepdims=False):
  x_float = tf.cast(x, tf.float32)
  mean = tf.reduce_mean(x_float,axis=axis,keepdims=keepdims)
  sq_diff = tf.square(x_float-mean)
  variance = tf.reduce_mean(sq_diff,axis=axis,keepdims=keepdims)
  return variance
variance_=compute_variance(E)
variance_

<tf.Tensor: shape=(), dtype=float32, numpy=906.5604858398438>

Standard Deviation : ` σ = sqrt(Σ (xi - μ)² / N)`

In [93]:
def compute_standard_scalar(x,axis=None,keepdims=False):
  # Cast the tensor to a floating-point type before calculating the standard deviation
  x_float = tf.cast(x, tf.float32)
  mean = tf.reduce_mean(x_float,axis=axis,keepdims=keepdims)
  sq_diff = tf.square(x_float-mean)
  variance = tf.reduce_mean(sq_diff,axis=axis,keepdims=keepdims)
  std = tf.sqrt(variance)
  return std
std_scalar = compute_standard_scalar(E)
std_scalar

<tf.Tensor: shape=(), dtype=float32, numpy=30.109142303466797>

## Simply using one liner code

In [94]:
tf.math.reduce_variance(tf.cast(E, tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=906.5604858398438>

In [95]:
tf.math.reduce_std(tf.cast(E, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.109142303466797>

## using tensorflow_probability as tfp

In [96]:
import tensorflow_probability as tfp

# Calculate the variance using tfp
variance_tfp = tfp.stats.variance(tf.cast(E, tf.float32))
print("Variance using tfp:", variance_tfp)

# Calculate the standard deviation using tfp
stddev_tfp = tfp.stats.stddev(tf.cast(E, tf.float32))
print("Standard deviation using tfp:", stddev_tfp)

Variance using tfp: tf.Tensor(906.5605, shape=(), dtype=float32)
Standard deviation using tfp: tf.Tensor(30.109142, shape=(), dtype=float32)


**Find the positional maximum and minimum of a tensor**

Row-Column wise max-min ber kora arki

In [97]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [98]:
# find the positional maximum returns an index
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [99]:
# find the value in that 42th position bro !
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [100]:
# checking if they are equal or not....asset deya mane false return hoile error dekhabe
assert F[tf.argmax(F)]==tf.reduce_max(F)

In [101]:
# finding the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [102]:
# find the value at that 16th position
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [103]:
assert F[tf.argmin(F)]==tf.reduce_min(F)

# Squezing a tensor (removing all single dimensions)

In [104]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [105]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [106]:
G_squeexed=tf.squeeze(G)
G_squeexed,G_squeexed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# One Hot Encoding Tensors

In [107]:
# create a list of indices
some_list=[0,1,2,3] # could be red,green,blue,purple

# one hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [108]:
# Specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="yo I love deep learning",off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

In [109]:
tf.one_hot(some_list,depth=4,on_value="yes!!!",off_value="no")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes!!!', b'no', b'no', b'no'],
       [b'no', b'yes!!!', b'no', b'no'],
       [b'no', b'no', b'yes!!!', b'no'],
       [b'no', b'no', b'no', b'yes!!!']], dtype=object)>

# Squaring ,log ,square root

In [110]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [111]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [112]:
# find the square root
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [113]:
# find the log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and Numpy

Tensorflow interacts beautifully with  Numpy Arrays

In [114]:
# Create a tensor directly from a Numpy array
J=tf.constant(np.array([3.,7.,10.]))
type(J)

tensorflow.python.framework.ops.EagerTensor

In [115]:
#converting our tensor back to a Numpy array
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [116]:
# convert tensor J to a numpy array
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [117]:
J=tf.constant([3.,4.5,6.7,3.2])
J.numpy()[2]

np.float32(6.7)

**The default types of each are slightly different**

In [118]:
numpy_J=tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])
# check the datatypes of each
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

# Python Decorators

In [119]:
def decorator(func):
    def a():
        print("Something is happening before the function is called.")
        func()
        print("Something is happening after the function is called.")
    return a

def say_whee():
    print("Whee!")

say_whee = decorator(say_whee) # deciration kine
say_whee()

Something is happening before the function is called.
Whee!
Something is happening after the function is called.


In [120]:
say_whee

<function __main__.decorator.<locals>.a()>

**Example**

In [121]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [122]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

If you noticed no difference between the above two functions (the decorated one and the non-decorated one) you'd be right.

Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.

# Finding access to GPUs

In [123]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [124]:
!nvidia-smi

Sun Jul 20 00:01:21 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   57C    P0             28W /   70W |     116MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----